#!/bin/sh

STAGING_D=/usr/local/etc/apache24/staging.d
PREFIX='2013site-'

if [ "$#" -ne 3 ]
then
  echo "[!] Usage: $0 NAME PORT DIRECTORY."
  echo "    (eg: $0 mattbw 8000 ~/2013site)"
  exit
fi

NAME="${PREFIX}$1"
FILE="${STAGING_D}/${NAME}.conf"
HOST="http://localhost:$2"


if [ -e "${FILE}" ]
then
  echo "[!] Staging website ${NAME} already exists."
  echo "    Please try a different name."
  exit
fi

if grep -q "${HOST}" ${STAGING_D}/*.conf
then
  echo "[!] Host ${HOST} is already in use."
  echo "    Please try a different port number."
  exit
fi

DIR=`echo $3 | sed 's|/$||'`
if [ ! \( -d "${DIR}" \) ]
then
  echo "[!] ${DIR} is not a directory."
  exit
fi


echo "[>] Creating ${NAME} for ${DIR} on host ${HOST}."

STANZA="/${NAME} ${HOST} retry=0"

echo "# Autogenerated by mkstaging - do not edit manually" > ${FILE}
echo "# DIR ${DIR}" >> $FILE
echo "ProxyPass ${STANZA}" >> $FILE
echo "ProxyPassReverse ${STANZA}" >> $FILE

